import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Col, ConfigProvider, Input, Layout, Popconfirm, Row, Select, Space, Switch, Table, Tabs, Tag, Typography, message } from 'antd';
import { CloseCircleOutlined, ReloadOutlined, ThunderboltOutlined } from '@ant-design/icons';
import AppSidebar from '@/layouts/AppSidebar';
import { useTheme } from '@/hooks/useTheme';
import { HttpUtil } from '@/utils';
import TrafficHistoryPanel from './TrafficHistoryPanel';

type ApiMsg<T=unknown>={success?:boolean;msg?:string;obj?:T}; type JsonObject=Record<string,unknown>;
type Connection={id:string;inbound?:string;inboundType?:string;source?:string;destination?:string;domain?:string;user?:string;outbound?:string;chain?:string[];uplink?:number;downlink?:number;uplinkTotal?:number;downlinkTotal?:number;createdAt?:number};
type Snapshot={config?:{outbounds?:JsonObject[]};running?:boolean;version?:string}; type Probe={tag?:string;success?:boolean;delay?:number;error?:string;mode?:string};
function bytes(v=0){if(!v)return'0 B';const u=['B','KiB','MiB','GiB'];let n=v,i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n>=10?n.toFixed(0):n.toFixed(1)} ${u[i]}`}
function tagOf(o:JsonObject){return typeof o.tag==='string'?o.tag:''} function typeOf(o:JsonObject){return typeof o.type==='string'?o.type:typeof o.protocol==='string'?o.protocol:''}

export default function SingBoxRuntimePage(){
 const {antdThemeConfig}=useTheme(); const [msgApi,ctx]=message.useMessage(); const [connections,setConnections]=useState<Connection[]>([]);const[outbounds,setOutbounds]=useState<JsonObject[]>([]);const[running,setRunning]=useState(false);const[version,setVersion]=useState('');const[resource,setResource]=useState('all');const[filter,setFilter]=useState('');const[auto,setAuto]=useState(true);const[loading,setLoading]=useState(false);const[testing,setTesting]=useState(false);const[results,setResults]=useState<Record<string,Probe>>({});
 const loadConfig=useCallback(async()=>{const m=await HttpUtil.get('/panel/api/setting/singbox/config',undefined,{silent:true}) as ApiMsg<Snapshot>;if(m.success&&m.obj){setRunning(!!m.obj.running);setVersion(m.obj.version||'');setOutbounds(Array.isArray(m.obj.config?.outbounds)?m.obj.config!.outbounds!:[])}},[]);
 const loadConnections=useCallback(async()=>{setLoading(true);try{const q:Record<string,string>={};if(resource!=='all')q.resource=resource;if(filter.trim())q.tag=filter.trim();const m=await HttpUtil.get('/panel/api/singbox/connections',q,{silent:true}) as ApiMsg<Connection[]>;if(!m.success)throw new Error(m.msg||'Failed to load sessions');setConnections(Array.isArray(m.obj)?m.obj:[])}catch(e){msgApi.error(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[filter,msgApi,resource]);
 const refresh=useCallback(async()=>{await Promise.all([loadConfig(),loadConnections()])},[loadConfig,loadConnections]);useEffect(()=>{void refresh()},[refresh]);useEffect(()=>{if(!auto)return;const id=window.setInterval(()=>void loadConnections(),5000);return()=>window.clearInterval(id)},[auto,loadConnections]);
 const close=async(id:string)=>{const m=await HttpUtil.post(`/panel/api/singbox/connections/${encodeURIComponent(id)}/close`);if(m.success)setConnections(v=>v.filter(x=>x.id!==id))};
 const testAll=async()=>{setTesting(true);try{const m=await HttpUtil.post('/panel/api/xray/testOutbounds',{outbounds:JSON.stringify(outbounds),mode:'tcp'}) as ApiMsg<Probe[]>;if(!m.success||!Array.isArray(m.obj))throw new Error(m.msg||'Probe failed');const r:Record<string,Probe>={};m.obj.forEach((x,i)=>{r[x.tag||tagOf(outbounds[i])||`#${i+1}`]=x});setResults(r)}catch(e){msgApi.error(e instanceof Error?e.message:String(e))}finally{setTesting(false)}};
 const opts=useMemo(()=>{const s=new Set<string>();connections.forEach(c=>{if(resource==='user'&&c.user)s.add(c.user);if(resource==='inbound'&&c.inbound)s.add(c.inbound);if(resource==='outbound'){if(c.outbound)s.add(c.outbound);c.chain?.forEach(x=>s.add(x))}});return[...s].sort()},[connections,resource]);
 const cols=[{title:'User',dataIndex:'user',width:130,render:(v:string)=>v||'—'},{title:'Source',dataIndex:'source',width:180,render:(v:string)=>v||'—'},{title:'Destination',render:(_:unknown,r:Connection)=>r.domain||r.destination||'—'},{title:'Inbound',dataIndex:'inbound',width:160,render:(v:string)=>v||'—'},{title:'Outbound',width:210,render:(_:unknown,r:Connection)=><Space direction="vertical" size={0}><span>{r.outbound||'—'}</span>{!!r.chain?.length&&<Typography.Text type="secondary">{r.chain.join(' → ')}</Typography.Text>}</Space>},{title:'Traffic',width:170,render:(_:unknown,r:Connection)=>`${bytes(r.uplinkTotal||r.uplink)} ↑ / ${bytes(r.downlinkTotal||r.downlink)} ↓`},{title:'',width:55,render:(_:unknown,r:Connection)=><Popconfirm title="Close connection?" onConfirm={()=>void close(r.id)}><Button danger type="text" icon={<CloseCircleOutlined/>}/></Popconfirm>}];
 const health=outbounds.map((o,i)=>{const name=tagOf(o)||`#${i+1}`;return{key:name,name,type:typeOf(o),result:results[name]}});
 return <ConfigProvider theme={antdThemeConfig}>{ctx}<Layout className="page-layout"><AppSidebar/><Layout className="content-shell"><Layout.Content id="content-layout" className="content-area"><Space direction="vertical" size={12} style={{width:'100%'}}><Card><Row align="middle"><Col flex="auto"><Typography.Title level={2} style={{margin:0}}>Sing-box Runtime</Typography.Title><Typography.Text type="secondary">Live sessions, traffic history and outbound health.</Typography.Text></Col><Col><Space><Tag color={running?'success':'default'}>{running?'running':'stopped'}</Tag>{version&&<Tag>{version}</Tag>}<Button icon={<ReloadOutlined/>} onClick={()=>void refresh()}>Refresh</Button></Space></Col></Row></Card>{!running&&<Alert type="warning" showIcon message="Sing-box is not running; live sessions are unavailable."/>}<Tabs items={[{key:'sessions',label:`Sessions (${connections.length})`,children:<Card><Space direction="vertical" size={12} style={{width:'100%'}}><Space wrap><Select value={resource} style={{width:150}} options={['all','user','inbound','outbound'].map(v=>({value:v,label:v}))} onChange={v=>{setResource(v);setFilter('')}}/>{resource==='all'?<Input value={filter} onChange={e=>setFilter(e.target.value)} allowClear placeholder="Filter tag" style={{width:280}}/>:<Select allowClear showSearch value={filter||undefined} options={opts.map(v=>({value:v,label:v}))} onChange={v=>setFilter(v||'')} style={{width:280}}/>}<Button loading={loading} onClick={()=>void loadConnections()}>Apply</Button><Switch checked={auto} onChange={setAuto}/><Typography.Text type="secondary">Auto 5s</Typography.Text></Space><Table rowKey="id" size="small" dataSource={connections} columns={cols} loading={loading} pagination={{pageSize:25}} scroll={{x:1100}}/></Space></Card>},{key:'health',label:'Outbound health',children:<Card><Space direction="vertical" size={12} style={{width:'100%'}}><Button type="primary" icon={<ThunderboltOutlined/>} loading={testing} onClick={()=>void testAll()}>Test all</Button><Table rowKey="key" size="small" dataSource={health} pagination={false} columns={[{title:'Tag',dataIndex:'name'},{title:'Type',dataIndex:'type',width:150},{title:'Status',width:140,render:(_:unknown,r:(typeof health)[number])=>!r.result?<Tag>not tested</Tag>:r.result.success?<Tag color="success">{r.result.delay||0} ms</Tag>:<Tag color="error">failed</Tag>},{title:'Details',render:(_:unknown,r:(typeof health)[number])=>r.result?.error||r.result?.mode||'—'}]}/></Space></Card>},{key:'history',label:'Traffic history',children:<TrafficHistoryPanel/>}]}/></Space></Layout.Content></Layout></Layout></ConfigProvider>
}
